# docker-compose.yml
version: '3.8' # 이 줄은 삭제해도 무방

services:
  web:
    build:
      context: . # 빌드 컨텍스트를 현재 디렉토리로 명시
      no_cache: true # 캐시를 사용하지 않고 빌드하도록 지시
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      env_file: ./.env
    depends_on:
      - redis
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - my-redis:/data

volumes:
  my-redis: